/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import javax.xml.bind.DatatypeConverter;

/**
 *
 * @author ivanr
 */
public class interfaz extends javax.swing.JFrame {
    
    private Biblioteca biblioteca = new Biblioteca();

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfIsbn = new javax.swing.JTextField();
        tfAutor = new javax.swing.JTextField();
        tfTitulo = new javax.swing.JTextField();
        tfPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfNoEjemplares = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnAgregarLibro = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfBuscarLibro = new javax.swing.JTextField();
        btnBuscarLibro = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tfIncrementarDecrementar = new javax.swing.JTextField();
        btnIncrementar = new javax.swing.JButton();
        btnDecrementar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        libroDetalle = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(50, 50));
        setSize(new java.awt.Dimension(1200, 900));

        jLabel1.setText("CAPTURAR INFORMACION");

        jLabel2.setText("ISBN");

        jLabel3.setText("Autor");

        jLabel4.setText("Titulo");

        tfIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIsbnActionPerformed(evt);
            }
        });

        tfAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAutorActionPerformed(evt);
            }
        });

        tfTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTituloActionPerformed(evt);
            }
        });

        tfPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrecioActionPerformed(evt);
            }
        });

        jLabel5.setText("Precio");

        tfNoEjemplares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoEjemplaresActionPerformed(evt);
            }
        });

        jLabel6.setText("No. de ejemplares");

        btnAgregarLibro.setText("Agregar Libro");
        btnAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLibroActionPerformed(evt);
            }
        });

        jLabel7.setText("BUSCAR LIBRO");

        tfBuscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarLibroActionPerformed(evt);
            }
        });

        btnBuscarLibro.setText("Buscar");
        btnBuscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarLibroActionPerformed(evt);
            }
        });

        jLabel8.setText("Existencia");

        btnIncrementar.setText("Incrementar");
        btnIncrementar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncrementarActionPerformed(evt);
            }
        });

        btnDecrementar.setText("Decrementar");
        btnDecrementar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecrementarActionPerformed(evt);
            }
        });

        jLabel9.setText("buscar por ISBN:");

        libroDetalle.setColumns(20);
        libroDetalle.setRows(5);
        jScrollPane1.setViewportView(libroDetalle);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfIsbn, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(tfAutor)
                            .addComponent(tfTitulo)
                            .addComponent(tfPrecio)
                            .addComponent(tfNoEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnAgregarLibro)))
                        .addGap(166, 166, 166)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfBuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarLibro)
                        .addGap(87, 87, 87)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
            .addGroup(layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfIncrementarDecrementar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIncrementar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDecrementar)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfBuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBuscarLibro)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfNoEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregarLibro)
                .addGap(153, 153, 153)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIncrementarDecrementar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDecrementar)
                    .addComponent(btnIncrementar))
                .addContainerGap(368, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAutorActionPerformed

    private void tfTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTituloActionPerformed

    private void tfPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrecioActionPerformed

    private void tfNoEjemplaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoEjemplaresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoEjemplaresActionPerformed

    private void btnAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLibroActionPerformed
        // TODO add your handling code here:
        
        if(biblioteca.getContador() < 4){
            String isbn = tfIsbn.getText();
            String autor = tfAutor.getText();
            String titulo = tfTitulo.getText();
            String precio = tfPrecio.getText();
            int ejemplaresExistentes = Integer.parseInt(tfNoEjemplares.getText());


            Libro libro = new Libro(isbn, autor, titulo, precio, ejemplaresExistentes);
            
            biblioteca.agregarColeccion(libro, biblioteca.getContador(), btnAgregarLibro);
            
            
            int num = biblioteca.getContador() + 1;
            biblioteca.setContador(num);
        }else{
            JOptionPane.showMessageDialog(btnAgregarLibro, "Capasidad maxima de lotes");
        }
        
        tfIsbn.setText("");
        tfAutor.setText("");
        tfTitulo.setText("");
        tfPrecio.setText("");
        tfNoEjemplares.setText("");
    }//GEN-LAST:event_btnAgregarLibroActionPerformed

    private void tfBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarLibroActionPerformed

    private void tfIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIsbnActionPerformed

    private void btnIncrementarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncrementarActionPerformed
        // TODO add your handling code here:
        //Incrementar
        String isbn = tfIncrementarDecrementar.getText();
        
        biblioteca.agregarLibro(isbn, btnIncrementar);
        
        tfIncrementarDecrementar.setText("");
        
    }//GEN-LAST:event_btnIncrementarActionPerformed

    private void btnBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLibroActionPerformed
        // TODO add your handling code here:
        
        /*
        al precionarce el boton, busca un libro especificndole su isbn
        */
        String isbn = tfBuscarLibro.getText();
        
        
        libroDetalle.setText(biblioteca.getLibroInfo(isbn, btnBuscarLibro));
        tfBuscarLibro.setText("");
    }//GEN-LAST:event_btnBuscarLibroActionPerformed

    private void btnDecrementarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecrementarActionPerformed
        // TODO add your handling code here:
        //Decrementar
        String isbn = tfIncrementarDecrementar.getText();
        
        biblioteca.venderLibro(isbn,1, btnDecrementar);
        
        tfIncrementarDecrementar.setText("");
        
    }//GEN-LAST:event_btnDecrementarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLibro;
    private javax.swing.JButton btnBuscarLibro;
    private javax.swing.JButton btnDecrementar;
    private javax.swing.JButton btnIncrementar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea libroDetalle;
    private javax.swing.JTextField tfAutor;
    private javax.swing.JTextField tfBuscarLibro;
    private javax.swing.JTextField tfIncrementarDecrementar;
    private javax.swing.JTextField tfIsbn;
    private javax.swing.JTextField tfNoEjemplares;
    private javax.swing.JTextField tfPrecio;
    private javax.swing.JTextField tfTitulo;
    // End of variables declaration//GEN-END:variables
}

class Biblioteca{

    public Biblioteca() {
        libros = mockLibros;
    }
    
    Libro[] mockLibros = {
        new Libro("","","", "", 0),
        new Libro("","","", "", 0),
        new Libro("","","", "", 0),
        new Libro("","","", "", 0)
    };

    private Libro libros[];
    private int contador = 0;

    public Libro[] getLibros() {
        return libros;
    }

    public int getContador() {
        return contador;
    }

    public void setContador(int contador) {
        this.contador = contador;
    }

    public void setLibros(Libro[] libros) {
        this.libros = libros;
    }

    public void getLibrosInfo() {
        System.out.println("Libro disponibles:");
        for(int i = 0; i < libros.length; i++){
            System.out.println(
                    "Titulo: "+libros[i].getTitulo().toUpperCase()+"\n"+
                    "ISBN: "+libros[i].getIsbn()+"\n"+
                    "Autor: "+libros[i].getAutor()+"\n"+
                    "Precio: "+libros[i].getPrecio()+"\n"+
                    "Existencia: "+libros[i].getEjemplaresExistentes()+"\n"+
                    "_____________________________________________"
            );
        }
    }
    
    public String getLibroInfo(String isbn, Component component){
        Libro libro = searchBook(isbn);
        
        if(libro == null){
            JOptionPane.showMessageDialog(component, "Libro no encontrado. Introdusca un ISBN valido.");
            return "";
        }
        
        return "Titulo: "+libro.getTitulo().toUpperCase()+"\n"+
        "ISBN: "+libro.getIsbn()+"\n"+
        "Autor: "+libro.getAutor()+"\n"+
        "Precio: "+libro.getPrecio()+"\n"+
        "Existencia: "+libro.getEjemplaresExistentes()+"\n"+
        "____________________________";
    }

    public void agregarLibro(String isbn, Component component){
        Libro libro = searchBook(isbn);
        if(libro == null){
            JOptionPane.showMessageDialog(component, "Libro no encontrado. Favor de introducir bien el ISBN");
            return;
        }
        libro.setEjemplaresExistentes(libro.getEjemplaresExistentes()+1);
        JOptionPane.showMessageDialog(component, "Se ha agregado un libro al inventario. Titulo: "+libro.getTitulo());
    }

    public void venderLibro(String isbn, int numeroVentas, Component component){
        Libro libro = searchBook(isbn);
        if(libro == null){
            JOptionPane.showMessageDialog(component, "Libro no encontrado. Favor de introducir bien el ISBN");
            return;
        }
        if((libro.getEjemplaresExistentes()-numeroVentas) >= 0){
            libro.setEjemplaresExistentes(libro.getEjemplaresExistentes()-numeroVentas);
            JOptionPane.showMessageDialog(component, "Libro "+libro.getTitulo()+" vendido correctamente.");
        }else {
            JOptionPane.showMessageDialog(component, "No quedan libros en el inventario");
        }
    }

    public Libro searchBook(String isbn){
        Libro libro = null;
        for(Libro searchLibro: libros){
            if(searchLibro.getIsbn().equals(isbn)) {
                libro = searchLibro;
                break;
            }
        }
        return libro;
    }
    
    public void agregarColeccion(Libro libro, int position, Component component){
        libros[position] = libro;
        JOptionPane.showMessageDialog(component, libro.getTitulo()+" guardado correctamente. ISBN: "+libro.getIsbn());
    }

}

class Libro {
    public Libro(String isbn, String autor, String titulo, String precio, int ejemplaresExistentes){
        this.isbn = isbn;
        this.autor = autor;
        this.titulo = titulo;
        this.precio = precio;
        this.ejemplaresExistentes = ejemplaresExistentes;
    }
    private String isbn;
    private String autor;
    private String titulo;
    private String precio;
    private int ejemplaresExistentes;

    public String getIsbn() {
        return isbn;
    }

    public String getAutor() {
        return autor;
    }

    public String getTitulo() {
        return titulo;
    }

    public String getPrecio() {
        return precio;
    }

    public int getEjemplaresExistentes() {
        return ejemplaresExistentes;
    }

    public void setEjemplaresExistentes(int ejemplaresExistentes) {
        this.ejemplaresExistentes = ejemplaresExistentes;
    }
}
